# Generated by Django 3.0.5 on 2020-12-02 16:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_loan_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bad_borrower',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 9, 16, 53, 51, 52204, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='beginning_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 2, 16, 53, 51, 51069, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='reference',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='biblio.Reference'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='beginning_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 2, 16, 53, 51, 49881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 1, 16, 53, 51, 49967, tzinfo=utc)),
        ),
    ]
