# Generated by Django 3.0.5 on 2020-12-02 21:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0003_auto_20201202_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='bad_borrower',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 9, 21, 19, 50, 53699, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='beginning_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 2, 21, 19, 50, 52892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 1, 21, 19, 50, 52927, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='beginning_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 2, 21, 19, 50, 52090, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 1, 21, 19, 50, 52151, tzinfo=utc)),
        ),
    ]
