# Generated by Django 3.0.5 on 2020-12-02 22:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0004_auto_20201202_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bad_borrower',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 9, 22, 35, 44, 203506, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='beginning_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 2, 22, 35, 44, 202671, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 1, 22, 35, 44, 202709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='beginning_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 2, 22, 35, 44, 201860, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 1, 22, 35, 44, 201924, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, max_length=5, verbose_name='Solde €'),
        ),
    ]
