# Generated by Django 3.0.5 on 2020-12-03 22:36

import biblio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0020_auto_20201203_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bad_borrower',
            name='ending_date',
            field=models.DateField(default=biblio.models.now_plus_2_year),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ending_date',
            field=models.DateField(default=biblio.models.now_plus_1_year),
        ),
    ]
