# Generated by Django 3.0.5 on 2020-12-04 18:28

import biblio.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0021_auto_20201203_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bad_borrower',
            options={'verbose_name': 'Mauvais utilisateur'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Emprunt'},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name': 'Ouvrage'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Abonnement'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur'},
        ),
        migrations.AlterField(
            model_name='bad_borrower',
            name='ending_date',
            field=models.DateField(default=biblio.models.now_plus_2_year, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='bad_borrower',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='beginning_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='ending_date',
            field=models.DateField(default=biblio.models.now_plus_30_days, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='reference',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='biblio.Reference', verbose_name='Ouvrage'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='returned',
            field=models.BooleanField(default=False, verbose_name='Retourné ?'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='publish_date',
            field=models.DateField(verbose_name='Date de Publication'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='beginning_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ending_date',
            field=models.DateField(default=biblio.models.now_plus_1_year, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
